### ISSUE TITLE
形容词一节最后的 DIV 似乎是错误了

### ISSUE THREAD

**Issue by xdxdy** [pizzamx/jpgramma#1]
在 http://res.wokanxing.info/jpgramma/adjectives.html 这个链接里。

<img width="792" alt="2018-03-28 11 30 54" src="https://user-images.githubusercontent.com/11024400/38005438-95fa4ae2-327b-11e8-9b26-471e60124755.png">

变成这样了😂

您看是不是酌情修一下？

**Comment by pizzamx** [comment]
多谢提醒……版本有点乱

Regards,
Tianying YANG

2018-03-28 10:32 GMT+08:00 xdxdy <notifications@github.com>:
