### ISSUE TITLE
用「まま」表示没有变化 这一节里面有翻译错误

### ISSUE THREAD

**Issue by billzt** [pizzamx/jpgramma#14]
英文原文：http://www.guidetojapanese.org/learn/grammar/nochange
「まま」, not to be confused with the childish expression for “mother” （ママ）, is a grammatical phrase to express a lack of change in something. Grammatically, it is used just like a regular **noun**.

译文：https://res.wokanxing.info/jpgramma/nochange.html
不要把「まま」跟小孩子叫的妈妈（ママ）搞混了，这是一个用来表示某物缺少改变的词。语法上看，它算是一个**动词**（错，应该是名词）。

**Comment by pizzamx** [comment]
thx
