### ISSUE TITLE
Bootstrap files from bootcdn give 404

### ISSUE THREAD

**Issue by Xdminsy** [pizzamx/jpgramma#19]
[jpgramma](https://res.wokanxing.info/jpgramma/)
Now the link gives 404.
And another problem is, the links of boostrap CSS and js files from bootcdn also give 404.
This causes the site to display incorrectly.

**Comment by Xdminsy** [comment]
Oh well, it now opens, I don't know why. maybe because of some problems with Github pages.
But bootstrap.css and bootstrap.min.js are still 404.

**Comment by pizzamx** [comment]
Man you really grasped the glitch...Yes the site went 404 for a while as my DNS was messed up, which happened  as a consequnce of my discovery of the bootstrap CDN problem yesterday.

Now I need some time to fix it as the new bootstrap API looks incompatible to me...

**Comment by Xdminsy** [comment]
哈哈哈那还真是巧啊。原来是这样。
之前看到样式没了自己换了下 jsdelivr cdn 接着用了 hh。
新年快乐哦ww。

**Comment by pizzamx** [comment]
fixed
