### ISSUE TITLE
Content are not centered.

### ISSUE THREAD

**Issue by Xdminsy** [pizzamx/jpgramma#20]
很高兴网站又正常了页面样式也在了。
就是有个比较明显的小问题看了一下他不居中了。
看了一下是 bootstrap 的 3 的 `col-*-offset-*` 在 4 里改成了 `offset-*-*`。
`col-lg-offset-2` `col-md-offset-2` 不起作用了。
改成 `offset-lg-2` 和 `offset-md-2` 就好了。

0.0 呃本来想直接改一下再提个 pr 的发现全是 html 成品文件，就不太清楚是怎么改的，是批量替换的么。
只能先提个 issue 询问一下了。

**Comment by pizzamx** [comment]
多谢老弟（妹），确实是土办法手改的哈
