### ISSUE TITLE
【修正建议】动词修饰名词

### ISSUE THREAD

**Issue by shincyan1900** [pizzamx/jpgramma#21]
你好！在[关系从句和语序](https://res.wokanxing.info/jpgramma/clause.html)一节，有提到

> 动词（译者注：这里可能说的是名词）的否定式、过去形和过去否定式都可以和形容词一样直接修饰名词。

下面是我的个人看法。

这里说的应该就是动词。原因有以下几点：

1. 动词修饰名词这点是确定的，除了否定式、过去形、过去否定式外，而连体形一般都和动词原型一致，所以一般也有简体形和连体形修饰名词的说法。

2. 这部分内容所属二级标题为“把动词和状态表示语当作形容词对待“，而除了这里提了一句外，在其他部分都没有提及此部分动词修饰名词的内容。

基于以上，把内容修正为：

>  动词的否定式、过去形和过去否定式都可以和形容词一样直接修饰名词。

也许更为稳妥。

**Comment by pizzamx** [comment]
谢谢，开头这段说的不是这一节的内容……
