### ISSUE TITLE
有计划翻译原作者的《complete guide》吗？

### ISSUE THREAD

**Issue by Nyte-BK201** [pizzamx/jpgramma#23]
我注意到17年后，原作者更新了另外一本手册，内容更循序渐进，也更齐全。覆盖了该本grammar的内容。内容已经相对稳定（我检查了内容，已经数年没有更新），感觉比较有价值。

**Comment by pizzamx** [comment]
没计划…我看了下目录好像也没啥本质区别啊

**Comment by orklann** [comment]
现在翻译的这本很好，虽然我是看原作的英文版。
