### ISSUE TITLE
日语书写系统中对于汉字的讨论

### ISSUE THREAD

**Issue by String10** [pizzamx/jpgramma#31]
原文为:
> In fact, it might not have been a good idea to adopt Chinese into Japanese since both languages are fundamentally different in many ways.

现在的翻译为:
> 日语和中文本来就风马牛不相及，所以也许使用汉字并不是个好主意。

DeepL给出的翻译为:
> 事实上，将中文引入日语可能并不是一个好主意，因为这两种语言在许多方面都有本质区别。

这里对于日语和中文之间的关系是否叙述的过于绝对? 据[维基百科](https://zh.wikipedia.org/wiki/%E6%97%A5%E8%AF%AD)叙述:
> 日语音韵中的拗音等就是来自于汉语，日语模仿古代汉语书面语的语法、语法的行为，使得人们在日语语法、语法和文体上都能看见汉语对日语的影响。日本属于以中国为中心的汉字文化圈。

仅表示建议, 希望译者可以考虑修改这一部分的表述, 谢谢.

**Comment by pizzamx** [comment]
谢谢，稍微改了点。时间太久了，如果校对一遍估计有很多不满意的……
