### ISSUE TITLE
形容词的未然形的翻译建议改为否定形

### ISSUE THREAD

**Issue by Asutorufa** [pizzamx/jpgramma#8]
日语翻译上的一点建议,文章中形容词的未然形建议改为否定形,日语官方的未然形活用语法是かろ,な形容词(形容动词)为だろ,而后面加ない应该是形容词的否定形式才对.

形容词

|未然形 | 連用形 | 終止形 | 連体形 | 仮定形 | 命令形|
|-- | -- | -- | -- | -- | --|
-かろ | -かっく | -い | -い | -けれ |  

形容动词

|未然形 | 連用形 | 終止形 | 連体形 | 仮定形 | 命令形|
|-- | -- | -- | -- | -- | --|
  | -だっ |   |   |   |  
-だろ | -で | -だ | -な | -なら |  
  | -に |   |   |   |  

还有动词的未然形也建议改成否定形.....

**Comment by pizzamx** [comment]
因为日语活用只有你列举的这六种形式，所以我也是直接使用了和制词。不知道你这个建议是否有国内正规教材之类的证据支持呢？

**Comment by Asutorufa** [comment]
> 因为日语活用只有你列举的这六种形式，所以我也是直接使用了和制词。不知道你这个建议是否有国内正规教材之类的证据支持呢？

我也没有正规的日语课本,只有一本蓝宝书上写的是ない形,但是我建议至少标注一下,不然对像我这种的新手学日语来说,可能会造成困惑.

**Comment by pizzamx** [comment]
我翻了一下，形容词的否定也就是一开始说了几句じゃない吧，这不重要，日语的重点难点在动词……再说了，「未然」不就是否定的意思么，哈哈，咋会困惑呢

**Comment by Asutorufa** [comment]
> 形容词的否定

比如有时候查单词会这样显示
```
白かろう
読み方：はくかろう、しろかろう
形容詞「白い」の未然形である「白かろ」に、推量の助動詞「う」が付いた形。
```
这时候这个未然形我就不太清楚了,感觉和我看过的好像不太一样,可能我的 脑回路比较奇葩.哈哈哈

**Comment by AuTa** [comment]
未然形：主要用来接续表示否定的助动词“-ない”，被动、可能助动词“-れる‧られる”，使役助动词“せる‧させる”，意志、推量助动词“う”等等。

未然形不止有否定的意思，而且形容词的否定并不是用未然形来否定。我们不能为了照顾教育文法，而把学校文法弄错。

[为什么日语中形容词连用形+ない，而动词却是未然形+ない？ - 知乎](https://www.zhihu.com/question/39082575/answer/79889667)

[活用 (日语) - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E6%B4%BB%E7%94%A8_(%E6%97%A5%E8%AA%9E))

**Comment by pizzamx** [comment]
> 未然形：主要用来接续表示否定的助动词“-ない”，被动、可能助动词“-れる‧られる”，使役助动词“せる‧させる”，意志、推量助动词“う”等等。
> 
> 未然形不止有否定的意思，而且形容词的否定并不是用未然形来否定。形容词、形容动词的未然形主要用来表推量。
> 
> 我们不能为了照顾教育文法，而把学校文法弄错。
> 
> [为什么日语中形容词连用形+ない，而动词却是未然形+ない？ - 知乎](https://www.zhihu.com/question/39082575/answer/79889667)
> 
> [活用 (日语) - 维基百科，自由的百科全书](https://zh.wikipedia.org/wiki/%E6%B4%BB%E7%94%A8_(%E6%97%A5%E8%AA%9E))

大哥您好，我感觉这份指南就是所谓的教育文法，而且我基本也只是在直译英文文本。现在的译本里面已经没有把“未然”跟“否定”等同了，只用否定式这个说法
